# Generated by Django 2.1.5 on 2019-01-30 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(max_length=200)),
                ('donor_email', models.CharField(max_length=1000)),
                ('donor_phone', models.IntegerField(unique=True)),
                ('donor_address', models.CharField(max_length=2000)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehousenum', models.IntegerField(unique=True)),
                ('invoicenum', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=300)),
                ('item_type', models.CharField(max_length=200)),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_test', models.CharField(choices=[('Y', 'Pass.'), ('N', 'Fail.')], max_length=100)),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_of_item', models.CharField(max_length=1000)),
                ('attribute_name', models.CharField(max_length=2000)),
                ('type_of_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='boards.Item')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='boards.Item'),
        ),
        migrations.AddField(
            model_name='donor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='boards.Item'),
        ),
        migrations.AddField(
            model_name='donor',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donors', to=settings.AUTH_USER_MODEL),
        ),
    ]
