# Generated by Django 2.1.5 on 2019-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='invoicenum',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='warehousenum',
            field=models.CharField(max_length=100),
        ),
    ]
